"""Tracks every tool a pipeline run actually calls, in order, so `code_generator_agent` can turn the
run into a standalone script instead of reconstructing it from prose.

`run_with_prompted_tools` in `console/run.py` is the one place a tool call actually executes —
`agent.toolbox.call(name, arguments)` — so `CodeTracker.record` is called from right beside it, once
the call has succeeded and after `with_known_data_path` has already filled in whatever the model left
out. What gets recorded is the *real* call: the tool's underlying function, the module it lives in, and
the exact keyword arguments it ran with — not what the model's own text claims it did, which is the
whole reason to build a script from this rather than from `agent_outputs`.

    tracker = CodeTracker()
    tracker.record(stage="data engineering", agent="data_reader_agent", tool=tool, arguments={...})
    ...
    tracker.render_calls()   # the block `code_generator_agent`'s prompt reads as `{context}`
    tracker.render_script()  # the deterministic scripts/main.py this class can write on its own
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ToolCallRecord:
    """One tool call, exactly as it ran."""

    stage: str
    agent: str
    tool: str
    module: str
    function: str
    arguments: dict[str, Any] = field(default_factory=dict)


class CodeTracker:
    """Collects every tool call a pipeline run makes, in the order it made them."""

    def __init__(self) -> None:
        self.calls: list[ToolCallRecord] = []

    def record(self, stage: str, agent: str, tool: Any, arguments: dict[str, Any]) -> None:
        """Record one successful call. `tool` is a `builder.tools.Tool`; its `.function` is the real
        callable `arguments` ran against, which is where the import path comes from — `tool.caller` is
        only a string, and in its module form (see `Tool.resolve_function`) does not name the function
        at all.
        """
        function = tool.function
        if function is None:  # a tool with no resolved function cannot have actually run
            return

        self.calls.append(
            ToolCallRecord(
                stage=stage,
                agent=agent,
                tool=tool.name,
                module=function.__module__,
                function=function.__name__,
                arguments=dict(arguments),
            )
        )

    def render_calls(self) -> str:
        """Every call rendered as real, pasteable Python — what `code_generator_agent` is told it may
        restructure, comment and rename around, but never change the substance of (see
        `prompts/code_generator.md`).
        """
        if not self.calls:
            return "(no tool calls were made during this run)"

        blocks = []
        for index, call in enumerate(self.calls, start=1):
            arguments = ", ".join(f"{name}={value!r}" for name, value in call.arguments.items())
            blocks.append(
                f"{index}. [{call.stage} / {call.agent}]\n"
                f"   from {call.module} import {call.function}\n"
                f"   {call.function}({arguments})"
            )
        return "\n\n".join(blocks)

    def render_script(self) -> str:
        """The `scripts/main.py` this class can generate entirely on its own: every call, in order,
        faithfully reproduced with real imports and its exact arguments. This is the deterministic
        fallback `run_pipeline` writes when `code_generator_agent` fails to answer, or answers with a
        script that `covers()` says has dropped a call — the same "not a request the model can decline"
        posture `with_known_data_path` already takes for a tool's `data_source` argument.
        """
        lines = [
            '"""Generated by the feature-store-agent pipeline: every tool call it actually ran, in order."""',
            "",
        ]
        imports = dict.fromkeys((call.module, call.function) for call in self.calls)
        for module, function in imports:
            lines.append(f"from {module} import {function}")

        lines.append("")
        lines.append("")
        lines.append("def main() -> None:")
        if not self.calls:
            lines.append("    pass  # no tool calls were recorded")
        for index, call in enumerate(self.calls, start=1):
            lines.append(f"    # {index}. [{call.stage}] {call.agent} -> {call.tool}")
            lines.append(f"    step_{index} = {call.function}(")
            for name, value in call.arguments.items():
                lines.append(f"        {name}={value!r},")
            lines.append("    )")
            lines.append(f"    print(step_{index})")
            lines.append("")

        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append("    main()")
        return "\n".join(lines) + "\n"

    def covers(self, script: str) -> bool:
        """Whether `script` still calls every function this tracker recorded — the check that decides
        whether a model-authored script is trustworthy enough to write out as-is, or whether
        `render_script`'s own deterministic version should be written instead.
        """
        return bool(self.calls) and all(call.function in script for call in self.calls)
